const SUCCESS_RESPONSE = { success: true };

const ROLLOUT_FEATURE_CONFIG_EVENT_TYPES = {
  ROLLOUT_FEATURE_CONFIG_EVENT_TYPES_UPDATED: "ROLLOUT_FEATURE_CONFIG_EVENT_TYPES_UPDATED"
};

module.exports = { SUCCESS_RESPONSE, ROLLOUT_FEATURE_CONFIG_EVENT_TYPES };
