const SUCCESS_RESPONSE = { success: true };

const FEATURE_CONFIGURATION_EVENT_TYPES = {
  FEATURE_CONFIGURATION_UPDATED: "FEATURE_CONFIGURATION_UPDATED",
  FEATURE_CONFIGURATION_CREATED: "FEATURE_CONFIGURATION_CREATED",
  FEATURE_CONFIGURATION_BULK_DATA_UPDATED: "FEATURE_CONFIGURATION_BULK_DATA_UPDATED"
};

module.exports = {
  SUCCESS_RESPONSE,
  FEATURE_CONFIGURATION_EVENT_TYPES
};
