const SUCCESS_RESPONSE = { success: true };

const OUTLET_CONFIG_EVENT_TYPES = {
  OUTLET_CONFIG_UPDATED: "OUTLET_CONFIG_UPDATED",
  OUTLET_CONFIG_CREATED: "OUTLET_CONFIG_CREATED",
  OUTLET_CONFIG_BULK_DATA_UPDATED: "OUTLET_CONFIG_BULK_DATA_UPDATED"
};

module.exports = { SUCCESS_RESPONSE, OUTLET_CONFIG_EVENT_TYPES };
