const SUCCESS_RESPONSE = { success: true };

const OUTLET_DEVICE_EVENT_TYPES = {
  OUTLET_DEVICE_UPDATED: "OUTLET_DEVICE_UPDATED",
  OUTLET_DEVICE_CREATED: "OUTLET_DEVICE_CREATED",
  OUTLET_DEVICE_BULK_DATA_UPDATED: "OUTLET_DEVICE_BULK_DATA_UPDATED"
};

module.exports = { SUCCESS_RESPONSE, OUTLET_DEVICE_EVENT_TYPES };
