const SUCCESS_RESPONSE = { success: true };

const TERMINAL_REGISTER_STATUS = {
  OPEN: "OPEN",
  CLOSE: "CLOSE",
  HOLD: "HOLD",
  RESUME: "RESUME"
};

const TERMINAL_STATUS = {
  BUSY: "BUSY",
  AVAILABLE: "AVAILABLE",
  SUSPENDED: "SUSPENDED"
};

const TERMINAL_USAGE_ACTION = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  FORCED_LOGOUT: "FORCED_LOGOUT",
  HOLD: "HOLD",
  RESUME: "RESUME"
};

const TERMINAL_EVENT_TYPES = {
  TERMINAL_UPDATED: "TERMINAL_UPDATED",
  TERMINAL_CREATED: "TERMINAL_CREATED",
  TERMINAL_BULK_DATA_UPDATE: "TERMINAL_BULK_DATA_UPDATE"
};

const TERMINAL_USAGE_EVENT_TYPES = {
  TERMINAL_USAGE_UPDATED: "TERMINAL_USAGE_UPDATED",
  TERMINAL_USAGE_CREATED: "TERMINAL_USAGE_CREATED"
};

const TERMINAL_REGISTER_EVENT_TYPES = {
  TERMINAL_REGISTER_UPDATED: "TERMINAL_REGISTER_UPDATED",
  TERMINAL_REGISTER_CREATED: "TERMINAL_REGISTER_CREATED"
};

const TERMINAL_USAGE_TERMINAL_STATUS_MAPPER = {
  [TERMINAL_USAGE_ACTION.LOGIN]: TERMINAL_STATUS.BUSY,
  [TERMINAL_USAGE_ACTION.LOGOUT]: TERMINAL_STATUS.AVAILABLE,
  [TERMINAL_USAGE_ACTION.FORCED_LOGOUT]: TERMINAL_STATUS.AVAILABLE
};

const PAYMENT_OPTION_CODES = {
  WALLET: "WALLET",
  CASH: "CASH",
  UPI: "UPI",
  CARD: "CARD"
};

module.exports = {
  SUCCESS_RESPONSE,
  TERMINAL_REGISTER_STATUS,
  TERMINAL_STATUS,
  TERMINAL_USAGE_ACTION,
  TERMINAL_USAGE_TERMINAL_STATUS_MAPPER,
  TERMINAL_EVENT_TYPES,
  TERMINAL_USAGE_EVENT_TYPES,
  TERMINAL_REGISTER_EVENT_TYPES,
  PAYMENT_OPTION_CODES
};
