const SUCCESS_RESPONSE = { success: true };

const POS_CONFIG_EVENT_TYPES = {
  POS_CONFIGURATION_UPDATED: "POS_CONFIGURATION_UPDATED",
  POS_CONFIGURATION_BULK_DATA_UPDATE: "POS_CONFIGURATION_BULK_DATA_UPDATE"
};

module.exports = {
  SUCCESS_RESPONSE,
  POS_CONFIG_EVENT_TYPES
};
